name: metro_pay
description: "MetroPay"


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  regexed_validator: ^2.0.0+1
  change_app_package_name: ^1.4.0
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  animation_wrappers: ^3.0.0
  flutter_polyline_points: ^2.1.0
  equatable: ^2.0.3
  dotted_border: ^2.0.0+3
  get: ^4.6.6
  auto_size_text: ^3.0.0
  http: ^1.2.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_svg: any
  email_validator: ^2.1.16
  pin_keyboard: ^1.1.2
  pin_code_fields: ^8.0.1
  recase: ^4.1.0
  device_info_plus: ^10.0.0
  permission_handler: ^10.0.0
  country_state_city: ^0.1.6
  nigerian_states_and_lga: ^1.0.0
  toggle_switch: ^2.3.0
  fluttermoji: ^1.0.2
  flash: ^3.1.1
  intl: ^0.19.0
  loading_btn: ^1.0.3
  flutter_spinkit: ^5.2.1
  restart_app: ^1.2.1
  flutter_phoenix: ^1.1.1
  smooth_page_indicator: ^1.0.0+2
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  pdf: ^3.11.1
  path_provider: ^2.0.5
  sentry_flutter: ^8.9.0
  web_socket_channel: ^3.0.1
  currency_code_to_currency_symbol: ^0.0.4
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/footer_icons/
    - assets/images/splash_logo.png
    - assets/images/splash_cover.png
    - assets/images/car.png
    - assets/images/first_img.svg
    - assets/images/second_img.svg
    - assets/images/third_img.svg
    - assets/images/person1.png
    - assets/images/person2.png
    - assets/images/person3.png
    - assets/images/person4.png
    - assets/images/person5.png
    - assets/images/person6.png
    - assets/images/folder-open.png


flutter_native_splash:
  background_image: assets/images/splash_cover.png

  android_12:
    background_image: assets/images/splash_cover.png

  android: true
  ios: true