name: african_countries
description: "African Countries"


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  hydrated_bloc: ^9.1.3
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  loading_btn: ^1.0.3
  flutter_spinkit: ^5.2.1
  auto_size_text: ^3.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  flash: ^3.1.1
  cached_network_image: ^3.4.1
  flutter_svg: any
  go_router: ^14.8.1
  pretty_animated_buttons: ^0.0.2
  transparent_image: ^2.0.1
  path_provider: ^2.1.2
  intl: ^0.20.2
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Paradroid
      fonts:
        - asset: fonts/paradroid.otf


flutter_native_splash:
  background_image: assets/images/splash_cover.png

  android_12:
    background_image: assets/images/splash_cover.png

  android: true
  ios: true